# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Legit Internal Traffic
email: legit@internal.traffic
description: >- # this means to ignore newlines until "baseurl:"
  LegitInternalTraffic.com is a blogging website to publish write-ups of awesome capture-the-flag
  challenges and interesting cyber security research. LegitInternalTraffic is a CTF group of 
  Dutch cyber security enthusiasts and professionals.
#baseurl: "/legit-internal-traffic"  #uncomment for publish
baseurl: ""                         #comment for publish 
#url: "daveystruijk.github.io"
url: "legitinternaltraffic.github.io"
#url: "localhost:4000"
permalink: /:title
twitter_username: LegitInternalTraffic
github_username:  LegitInternalTraffic

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
